In [2]:
import pandas as pd

train = pd.read_csv("../data/train.csv", low_memory=False)
test = pd.read_csv("../data/test.csv", low_memory=False)

train.head()

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0,spoofed
0,0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,ch0,0
1,0,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,ch1,0
2,0,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,ch2,0
3,0,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,ch3,0
4,0,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,ch4,0

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891216 entries, 0 to 891215
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   time                891216 non-null  int64
 1   channel             891216 non-null  object
 2   PRN                 891216 non-null  object
 3   Carrier_Doppler_hz  891216 non-null  object
 4   Pseudorange_m       891216 non-null  object
 5   RX_time             891216 non-null  object
 6   TOW                 891216 non-null  object
 7   Carrier_phase       891216 non-null  object
 8   EC                  891216 non-null  object
 9   LC                  891216 non-null  object
 10  PC                  891216 non-null  object
 11  PIP                 891216 non-null  object
 12  PQP                 891216 non-null  object
 13  TCD                 891216 non-null  object
 14  CN0                 891216 non-null  object
 15  spoofed             891216 non-null  int64
dtypes: int64(2), object(14)
memory usage: 108.8+ MB

In [6]:
train.iloc[100:110]

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0,spoofed
100,12,ch4,0,0,0,0,0,0,0,0,0,0,0,0,0,0
101,12,ch5,0,0,0,0,0,0,0,0,0,0,0,0,0,0
102,12,ch6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
103,12,ch7,0,0,0,0,0,0,0,0,0,0,0,0,0,0
104,13,ch0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
105,13,ch1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
106,13,ch2,0,0,0,0,0,0,0,0,0,0,0,0,0,0
107,13,ch3,0,0,0,0,0,0,0,0,0,0,0,0,0,0
108,13,ch4,0,0,0,0,0,0,0,0,0,0,0,0,0,0
109,13,ch5,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
cols = ['PRN','Carrier_Doppler_hz','Pseudorange_m','RX_time','TOW',
        'Carrier_phase','EC','LC','PC','PIP','PQP','TCD','CN0']

for c in cols:
    train[c] = pd.to_numeric(train[c], errors='coerce')

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891216 entries, 0 to 891215
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   time                891216 non-null  int64
 1   channel             891216 non-null  object
 2   PRN                 891208 non-null  float64
 3   Carrier_Doppler_hz  891208 non-null  float64
 4   Pseudorange_m       891208 non-null  float64
 5   RX_time             891208 non-null  float64
 6   TOW                 891208 non-null  float64
 7   Carrier_phase       891208 non-null  float64
 8   EC                  891208 non-null  float64
 9   LC                  891208 non-null  float64
 10  PC                  891208 non-null  float64
 11  PIP                 891208 non-null  float64
 12  PQP                 891208 non-null  float64
 13  TCD                 891208 non-null  float64
 14  CN0                 891208 non-null  float64
 15  spoofed             891216 non-null  int64
dtypes: float64(13), int64(2), object(1)
memory usage: 108.8+ MB

In [8]:
train.isnull().sum()

time                  0
channel               0
PRN                   8
Carrier_Doppler_hz    8
Pseudorange_m         8
RX_time               8
TOW                   8
Carrier_phase         8
EC                    8
LC                    8
PC                    8
PIP                   8
PQP                   8
TCD                   8
CN0                   8
spoofed               0
dtype: int64

In [9]:
train = train.dropna()
train.isnull().sum()

time                  0
channel               0
PRN                   0
Carrier_Doppler_hz    0
Pseudorange_m         0
RX_time               0
TOW                   0
Carrier_phase         0
EC                    0
LC                    0
PC                    0
PIP                   0
PQP                   0
TCD                   0
CN0                   0
spoofed               0
dtype: int64

In [10]:
train['channel'] = train['channel'].str.replace('ch','').astype(int)
train.head()

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0,spoofed
8,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
10,1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
11,1,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12,1,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [11]:
train = train.reset_index(drop=True)
train.head()

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0,spoofed
0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,1,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,1,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [12]:
X = train.drop('spoofed', axis=1)
y = train['spoofed']

print(X.shape)
print(y.shape)

(891208, 15)
(891208,)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_val.shape)

(712966, 15)
(178242, 15)

In [14]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [15]:
from sklearn.metrics import f1_score

val_pred = model.predict(X_val)

f1 = f1_score(y_val, val_pred, average='weighted')
print("Weighted F1 Score:", f1)

Weighted F1 Score: 1.0

In [16]:
y.value_counts()

spoofed
0    763880
1    127328
Name: count, dtype: int64

In [17]:
X = train.drop(['spoofed','time'], axis=1)

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [18]:
model.fit(X_train, y_train)

val_pred = model.predict(X_val)

from sklearn.metrics import f1_score
print(f1_score(y_val, val_pred, average='weighted'))

0.9745622513301999

In [19]:
test = pd.read_csv("../data/test.csv", low_memory=False)

In [20]:
test.head()

,time,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0
0,111402,ch0,8,4749.068417,4.841489e+06,263154.82,263154.803851,-435396.111594,101998.429688,100788.812500,111415.289062,-107731.039062,-28414.615234,4660.467773,43.559540
1,111402,ch1,9,1995.777378,2.449848e+06,263154.82,263154.811828,-201479.950180,100812.039062,98424.367188,109174.476562,-105347.234375,-28653.570312,1997.164185,47.116425
2,111402,ch2,27,3458.024120,3.738822e+06,263154.82,263154.807529,-356000.635312,138335.140625,125640.570312,138446.281250,137254.781250,-18124.476562,3467.803955,45.687332
3,111402,ch3,26,-2105.992470,5.482371e+06,263154.82,263154.801713,193102.504674,84470.195312,84153.156250,95917.468750,95899.140625,1874.903442,-2109.972656,42.264256
4,111402,ch4,4,-493.638193,2.666526e+06,263154.82,263154.811105,48203.346004,103226.210938,100365.203125,114574.656250,-114160.539062,-9732.571289,-494.215881,43.629795

In [21]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381952 entries, 0 to 381951
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   time                381952 non-null  int64
 1   channel             381952 non-null  object
 2   PRN                 381952 non-null  int64
 3   Carrier_Doppler_hz  381952 non-null  float64
 4   Pseudorange_m       381952 non-null  float64
 5   RX_time             381952 non-null  float64
 6   TOW                 381952 non-null  float64
 7   Carrier_phase       381952 non-null  float64
 8   EC                  381952 non-null  float64
 9   LC                  381952 non-null  float64
 10  PC                  381952 non-null  float64
 11  PIP                 381952 non-null  float64
 12  PQP                 381952 non-null  float64
 13  TCD                 381952 non-null  float64
 14  CN0                 381952 non-null  float64
dtypes: float64(12), int64(2), object(1)
memory usage: 43.7+ MB

In [22]:
test['channel'] = test['channel'].str.replace('ch','').astype(int)

In [23]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381952 entries, 0 to 381951
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   time                381952 non-null  int64
 1   channel             381952 non-null  int64
 2   PRN                 381952 non-null  int64
 3   Carrier_Doppler_hz  381952 non-null  float64
 4   Pseudorange_m       381952 non-null  float64
 5   RX_time             381952 non-null  float64
 6   TOW                 381952 non-null  float64
 7   Carrier_phase       381952 non-null  float64
 8   EC                  381952 non-null  float64
 9   LC                  381952 non-null  float64
 10  PC                  381952 non-null  float64
 11  PIP                 381952 non-null  float64
 12  PQP                 381952 non-null  float64
 13  TCD                 381952 non-null  float64
 14  CN0                 381952 non-null  float64
dtypes: float64(12), int64(3)
memory usage: 43.7 MB

In [24]:
test = test.drop('time', axis=1)

In [25]:
test_pred = model.predict(test)

In [26]:
submission = pd.DataFrame({
    "spoofed": test_pred
})

submission.to_csv("../submission.csv", index=False)

submission.head()

   spoofed
0        0
1        0
2        0
3        0
4        0

In [27]:
import numpy as np
np.unique(test_pred, return_counts=True)

(array([0]), array([381952]))

In [28]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight='balanced'
)

model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                       random_state=42)

In [29]:
test_pred = model.predict(test)

import numpy as np
np.unique(test_pred, return_counts=True)

(array([0]), array([381952]))

In [30]:
test.head()

,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0
0,0,8,4749.068417,4.841489e+06,263154.82,263154.803851,-435396.111594,101998.429688,100788.812500,111415.289062,-107731.039062,-28414.615234,4660.467773,43.559540
1,1,9,1995.777378,2.449848e+06,263154.82,263154.811828,-201479.950180,100812.039062,98424.367188,109174.476562,-105347.234375,-28653.570312,1997.164185,47.116425
2,2,27,3458.024120,3.738822e+06,263154.82,263154.807529,-356000.635312,138335.140625,125640.570312,138446.281250,137254.781250,-18124.476562,3467.803955,45.687332
3,3,26,-2105.992470,5.482371e+06,263154.82,263154.801713,193102.504674,84470.195312,84153.156250,95917.468750,95899.140625,1874.903442,-2109.972656,42.264256
4,4,4,-493.638193,2.666526e+06,263154.82,263154.811105,48203.346004,103226.210938,100365.203125,114574.656250,-114160.539062,-9732.571289,-494.215881,43.629795

In [31]:
test.describe()

,channel,PRN,Carrier_Doppler_hz,Pseudorange_m,RX_time,TOW,Carrier_phase,EC,LC,PC,PIP,PQP,TCD,CN0
count,381952.000000,381952.000000,381952.000000,3.819520e+05,381952.000000,381952.000000,3.819520e+05,381952.000000,381952.000000,381952.000000,381952.000000,381952.000000,381952.000000,381952.000000
mean,3.500000,7.067330,858.034945,1.808115e+06,187069.660191,129625.207520,-8.174679e+04,53236.344587,53224.766115,58991.162326,-17.659814,-3.181736,860.580448,22.082173
std,2.291291,9.677686,1803.392877,2.098206e+06,119679.962057,131784.248457,1.883990e+05,58027.524599,57969.271004,64048.034747,85887.775047,14332.022690,1803.344803,22.524074
min,0.000000,0.000000,-2859.032425,0.000000e+00,0.000000,0.000000,-1.032332e+06,0.000000,0.000000,0.000000,-270777.625000,-192470.062500,-2333.721680,0.000000
25%,1.750000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-1.470773e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.500000,0.000000,0.000000,0.000000e+00,263449.150000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5.250000,9.000000,2139.469612,3.334400e+06,263753.305000,263633.111592,0.000000e+00,109760.539062,109717.214844,121862.380859,0.000000,0.000000,2138.988953,45.478316
max,7.000000,30.000000,5006.664021,6.858907e+06,264109.680000,264109.675669,2.609114e+05,239576.562500,244650.390625,271466.125000,235842.562500,200493.656250,4859.546875,49.958927

In [32]:
import numpy as np
np.unique(val_pred, return_counts=True)

(array([0, 1]), array([157209,  21033]))

In [33]:
submission['spoofed'].value_counts()

spoofed
0    381952
Name: count, dtype: int64

In [37]:
sample = pd.read_csv("../data/submission_format.csv")
sample.head()

     time  Spoofed  Confidence
0  111402      NaN         NaN
1  111403      NaN         NaN
2  111404      NaN         NaN
3  111405      NaN         NaN
4  111406      NaN         NaN

In [39]:
test['pred'] = test_pred

In [41]:
test = pd.read_csv("../data/test.csv", low_memory=False)

In [42]:
test['channel'] = test['channel'].str.replace('ch','').astype(int)

In [43]:
cols = ['PRN','Carrier_Doppler_hz','Pseudorange_m','RX_time','TOW',
        'Carrier_phase','EC','LC','PC','PIP','PQP','TCD','CN0']

for c in cols:
    test[c] = pd.to_numeric(test[c], errors='coerce')

test = test.dropna()

In [44]:
X_test = test.drop('time', axis=1)

In [45]:
test_pred = model.predict(X_test)

In [46]:
test['pred'] = test_pred

In [47]:
time_pred = test.groupby('time')['pred'].max().reset_index()
time_pred.head()

     time  pred
0  111402     0
1  111403     0
2  111404     0
3  111405     0
4  111406     0

In [49]:
sample = pd.read_csv("../data/submission_format.csv")

sample['Spoofed'] = time_pred['pred']
sample['Confidence'] = 1

In [50]:
sample.to_csv("../submission_final.csv", index=False)
sample.head()

     time  Spoofed  Confidence
0  111402        0           1
1  111403        0           1
2  111404        0           1
3  111405        0           1
4  111406        0           1

In [51]:
sample.to_csv("../submission_final.csv", index=False)

In [53]:
import pandas as pd

importance = pd.DataFrame({
    'feature': X_train.columns,
    'importance': model.feature_importances_
})

importance.sort_values(by='importance', ascending=False)

               feature  importance
4              RX_time    0.699451
5                  TOW    0.173170
3        Pseudorange_m    0.029259
13                 CN0    0.018010
12                 TCD    0.015741
2   Carrier_Doppler_hz    0.014249
1                  PRN    0.010552
0              channel    0.009279
6        Carrier_phase    0.008661
9                   PC    0.008362
8                   LC    0.007597
7                   EC    0.005636
10                 PIP    0.000023
11                 PQP    0.000010

In [54]:
train['time_diff'] = train['RX_time'] - train['TOW']

In [55]:
X = train.drop('spoofed', axis=1)
y = train['spoofed']

In [56]:
train['corr_diff'] = train['EC'] - train['LC']

In [57]:
X = train.drop('spoofed', axis=1)
y = train['spoofed']

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight='balanced'
)

model.fit(X_train, y_train)

val_pred = model.predict(X_val)

print("F1:", f1_score(y_val, val_pred, average='weighted'))

F1: 1.0

In [59]:
train = train.drop(['RX_time','TOW'], axis=1)

In [60]:
X = train.drop('spoofed', axis=1)
y = train['spoofed']

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1,
    class_weight='balanced'
)

model.fit(X_train, y_train)

val_pred = model.predict(X_val)

print("F1:", f1_score(y_val, val_pred, average='weighted'))

F1: 1.0

In [62]:
print(X.columns)

Index(['time', 'channel', 'PRN', 'Carrier_Doppler_hz', 'Pseudorange_m',
       'Carrier_phase', 'EC', 'LC', 'PC', 'PIP', 'PQP', 'TCD', 'CN0',
       'time_diff', 'corr_diff'],
      dtype='object')

In [63]:
import numpy as np
np.unique(val_pred, return_counts=True)

(array([0, 1]), array([152849,  25393]))

In [64]:
import pandas as pd

importance = pd.DataFrame({
    "feature": X_train.columns,
    "importance": model.feature_importances_
}).sort_values("importance", ascending=False)

print(importance)

               feature  importance
0                 time    0.616048
13           time_diff    0.222970
4        Pseudorange_m    0.053989
11                 TCD    0.024228
3   Carrier_Doppler_hz    0.023566
12                 CN0    0.013055
2                  PRN    0.012950
1              channel    0.012859
5        Carrier_phase    0.009276
8                   PC    0.004117
6                   EC    0.003530
7                   LC    0.003137
9                  PIP    0.000143
14           corr_diff    0.000093
10                 PQP    0.000038

In [65]:
train = train.drop(['time', 'time_diff'], axis=1)

In [66]:
X = train.drop('spoofed', axis=1)
y = train['spoofed']

In [67]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1,
    class_weight='balanced'
)

model.fit(X_train, y_train)

val_pred = model.predict(X_val)

print("F1:", f1_score(y_val, val_pred, average='weighted'))

F1: 0.7833240493218306

In [68]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import f1_score

model = HistGradientBoostingClassifier(
    max_iter=200,
    learning_rate=0.05,
    max_depth=8
)

model.fit(X_train, y_train)

val_pred = model.predict(X_val)

print("F1:", f1_score(y_val, val_pred, average='weighted'))

F1: 0.8893129883490667

In [69]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import HistGradientBoostingClassifier

model = HistGradientBoostingClassifier(
    max_iter=200,
    learning_rate=0.05,
    max_depth=8
)

scores = cross_val_score(
    model, X, y,
    scoring='f1_weighted',
    cv=5,
    n_jobs=-1
)

print("CV scores:", scores)
print("Mean F1:", scores.mean())

CV scores: [0.8013133  0.86936892 0.76810356 0.83057689 0.82020876]
Mean F1: 0.8179142866633408

In [71]:
train = pd.read_csv("../data/train.csv", low_memory=False)

In [72]:
train['channel'] = train['channel'].str.replace('ch','').astype(int)

In [73]:
cols = ['PRN','Carrier_Doppler_hz','Pseudorange_m','RX_time','TOW',
        'Carrier_phase','EC','LC','PC','PIP','PQP','TCD','CN0']

for c in cols:
    train[c] = pd.to_numeric(train[c], errors='coerce')

train = train.dropna()

In [74]:
train['CN0_mean_time'] = train.groupby('time')['CN0'].transform('mean')
train['doppler_mean_time'] = train.groupby('time')['Carrier_Doppler_hz'].transform('mean')
train['pseudo_mean_time'] = train.groupby('time')['Pseudorange_m'].transform('mean')

In [75]:
train['corr_diff'] = train['EC'] - train['LC']

In [76]:
train = train.drop(['RX_time','TOW'], axis=1)

In [77]:
X = train.drop('spoofed', axis=1)
y = train['spoofed']

In [78]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import f1_score

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = HistGradientBoostingClassifier(
    max_iter=300,
    learning_rate=0.05,
    max_depth=8
)

model.fit(X_train, y_train)

val_pred = model.predict(X_val)

print("F1:", f1_score(y_val, val_pred, average='weighted'))

F1: 0.9986224902539458

In [79]:
unique_times = train['time'].unique()

from sklearn.model_selection import train_test_split
train_times, val_times = train_test_split(unique_times, test_size=0.2, random_state=42)

train_df = train[train['time'].isin(train_times)]
val_df = train[train['time'].isin(val_times)]

X_train = train_df.drop('spoofed', axis=1)
y_train = train_df['spoofed']

X_val = val_df.drop('spoofed', axis=1)
y_val = val_df['spoofed']

In [80]:
model.fit(X_train, y_train)
val_pred = model.predict(X_val)

from sklearn.metrics import f1_score
print("F1:", f1_score(y_val, val_pred, average='weighted'))

F1: 0.9993945234550222

In [81]:
model = HistGradientBoostingClassifier(
    max_iter=300,
    learning_rate=0.05,
    max_depth=8
)

model.fit(X, y)

HistGradientBoostingClassifier(learning_rate=0.05, max_depth=8, max_iter=300)

In [84]:
test = pd.read_csv("../data/test.csv", low_memory=False)

test['channel'] = test['channel'].str.replace('ch','').astype(int)

for c in cols:
    test[c] = pd.to_numeric(test[c], errors='coerce')

test = test.dropna()

test['CN0_mean_time'] = test.groupby('time')['CN0'].transform('mean')
test['doppler_mean_time'] = test.groupby('time')['Carrier_Doppler_hz'].transform('mean')
test['pseudo_mean_time'] = test.groupby('time')['Pseudorange_m'].transform('mean')

test['corr_diff'] = test['EC'] - test['LC']

test = test.drop(['RX_time','TOW'], axis=1)

In [87]:
# Load test data
test = pd.read_csv("../data/test.csv", low_memory=False)

# Fix channel
test['channel'] = test['channel'].str.replace('ch','').astype(int)

# Convert numeric columns
cols = ['PRN','Carrier_Doppler_hz','Pseudorange_m','RX_time','TOW',
        'Carrier_phase','EC','LC','PC','PIP','PQP','TCD','CN0']

for c in cols:
    test[c] = pd.to_numeric(test[c], errors='coerce')

test = test.dropna()

# Create same features as training
test['CN0_mean_time'] = test.groupby('time')['CN0'].transform('mean')
test['doppler_mean_time'] = test.groupby('time')['Carrier_Doppler_hz'].transform('mean')
test['pseudo_mean_time'] = test.groupby('time')['Pseudorange_m'].transform('mean')

test['corr_diff'] = test['EC'] - test['LC']

# Remove leakage features
test = test.drop(['RX_time','TOW'], axis=1)

# Prepare test features (same columns as training)
X_test = test[X.columns]

# Predict
test_pred = model.predict(X_test)

test['pred'] = test_pred

# Convert to time-level predictions
time_pred = test.groupby('time')['pred'].max().reset_index()

# Load submission format
sample = pd.read_csv("../data/submission_format.csv")

sample['Spoofed'] = time_pred['pred']
sample['Confidence'] = 1

# Save submission
sample.to_csv("../submission_final.csv", index=False)

sample.head()

     time  Spoofed  Confidence
0  111402        0           1
1  111403        0           1
2  111404        0           1
3  111405        0           1
4  111406        0           1

In [88]:
sample.to_csv("../submission_final.csv", index=False)

In [89]:
sample.shape
sample.isnull().sum()
sample['Spoofed'].value_counts()

Spoofed
0    47744
Name: count, dtype: int64

In [90]:
test['pred'].value_counts()

pred
0    381952
Name: count, dtype: int64

In [91]:
# Load test data
test = pd.read_csv("../data/test.csv", low_memory=False)

# Fix channel column
test['channel'] = test['channel'].str.replace('ch','').astype(int)

# Convert numeric columns
cols = ['PRN','Carrier_Doppler_hz','Pseudorange_m','RX_time','TOW',
        'Carrier_phase','EC','LC','PC','PIP','PQP','TCD','CN0']

for c in cols:
    test[c] = pd.to_numeric(test[c], errors='coerce')

test = test.dropna()

# Create same engineered features as training
test['CN0_mean_time'] = test.groupby('time')['CN0'].transform('mean')
test['doppler_mean_time'] = test.groupby('time')['Carrier_Doppler_hz'].transform('mean')
test['pseudo_mean_time'] = test.groupby('time')['Pseudorange_m'].transform('mean')

test['corr_diff'] = test['EC'] - test['LC']

# Remove leakage features
test = test.drop(['RX_time','TOW'], axis=1)

# Make sure feature order matches training
X_test = test[X.columns]

# Predict probabilities
test_prob = model.predict_proba(X_test)[:,1]

# Apply lower threshold for imbalanced data
test_pred = (test_prob > 0.3).astype(int)

test['pred'] = test_pred

# Convert channel-level predictions to time-level
time_pred = test.groupby('time')['pred'].max().reset_index()

# Load required submission format
sample = pd.read_csv("../data/submission_format.csv")

sample['Spoofed'] = time_pred['pred']
sample['Confidence'] = 1

# Save final submission file
sample.to_csv("../submission_final.csv", index=False)

# Quick check
print(sample.head())
print(sample['Spoofed'].value_counts())

     time  Spoofed  Confidence
0  111402        0           1
1  111403        0           1
2  111404        0           1
3  111405        0           1
4  111406        0           1
Spoofed
0    47744
Name: count, dtype: int64

In [92]:
print(test_prob.min(), test_prob.max())

4.198619339414713e-08 1.18435023894893e-07

In [93]:
import numpy as np
print(np.percentile(test_prob, [50, 90, 95, 99]))

[7.17622818e-08 7.70465788e-08 8.14722827e-08 8.44765608e-08]

In [94]:
# -------------------------------
# LOAD TEST DATA
# -------------------------------
test = pd.read_csv("../data/test.csv", low_memory=False)

# Fix channel column
test['channel'] = test['channel'].str.replace('ch','').astype(int)

# Convert numeric columns
cols = ['PRN','Carrier_Doppler_hz','Pseudorange_m','RX_time','TOW',
        'Carrier_phase','EC','LC','PC','PIP','PQP','TCD','CN0']

for c in cols:
    test[c] = pd.to_numeric(test[c], errors='coerce')

test = test.dropna()

# -------------------------------
# FEATURE ENGINEERING (same as training)
# -------------------------------
test['CN0_mean_time'] = test.groupby('time')['CN0'].transform('mean')
test['doppler_mean_time'] = test.groupby('time')['Carrier_Doppler_hz'].transform('mean')
test['pseudo_mean_time'] = test.groupby('time')['Pseudorange_m'].transform('mean')

test['corr_diff'] = test['EC'] - test['LC']

# Remove leakage features
test = test.drop(['RX_time','TOW'], axis=1)

# -------------------------------
# PREPARE FEATURES
# -------------------------------
X_test = test[X.columns]

# -------------------------------
# MODEL PREDICTION
# -------------------------------
test_pred = model.predict(X_test)

test['pred'] = test_pred

# -------------------------------
# CONVERT CHANNEL → TIME LEVEL
# -------------------------------
time_pred = test.groupby('time')['pred'].max().reset_index()

# -------------------------------
# LOAD SUBMISSION FORMAT
# -------------------------------
submission = pd.read_csv("../data/submission_format.csv")

submission['Spoofed'] = time_pred['pred']
submission['Confidence'] = 1

# -------------------------------
# SAVE FINAL FILE
# -------------------------------
submission.to_csv("../submission_final.csv", index=False)

# Quick verification
print(submission.head())
print(submission['Spoofed'].value_counts())

     time  Spoofed  Confidence
0  111402        0           1
1  111403        0           1
2  111404        0           1
3  111405        0           1
4  111406        0           1
Spoofed
0    47744
Name: count, dtype: int64

In [95]:
submission.shape
submission.isnull().sum()

time          0
Spoofed       0
Confidence    0
dtype: int64

In [96]:
train_pred = model.predict(X)

import numpy as np
np.unique(train_pred, return_counts=True)

(array([0, 1]), array([762612, 128596]))

In [97]:
submission.shape
submission.isnull().sum()
submission.head()

     time  Spoofed  Confidence
0  111402        0           1
1  111403        0           1
2  111404        0           1
3  111405        0           1
4  111406        0           1

In [98]:
submission.shape

(47744, 3)

In [99]:
submission.isnull().sum()

time          0
Spoofed       0
Confidence    0
dtype: int64

In [100]:
submission.to_csv("submission_final.csv", index=False)

In [101]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import f1_score

model = HistGradientBoostingClassifier(
    max_iter=300,
    learning_rate=0.05,
    max_depth=8,
    class_weight="balanced"
)

model.fit(X_train, y_train)

val_pred = model.predict(X_val)

print("F1:", f1_score(y_val, val_pred, average='weighted'))

F1: 0.9982036948704941

In [102]:
test_pred = model.predict(X_test)
test['pred'] = test_pred

test['pred'].value_counts()

pred
0    381952
Name: count, dtype: int64

In [103]:
test_prob = model.predict_proba(X_test)[:,1]

test['prob'] = test_prob

In [104]:
test['prob'].describe()

count    3.819520e+05
mean     2.559000e-07
std      3.606866e-08
min      1.501388e-07
25%      2.505876e-07
50%      2.738539e-07
75%      2.738539e-07
max      4.591669e-07
Name: prob, dtype: float64